# Generated by Django 4.2.3 on 2023-07-12 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_accounts_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accounts',
            options={'ordering': ['password1']},
        ),
    ]
